version: '3.4'

services:
  app:
    image: docker.nuyken.dev/fhdw-me-saf-22-monolith/app:1.0.0
    restart: unless-stopped
    environment:
      CONNECTION_STRING: "Host=db;Port=5432;Database=postgres;Username=postgres;Password=password"
      DATABASE__AUTOMIGRATE: "true"
      DATABASE__TYPE: "postgres"
      SWAGGER__PUBLISHSWAGGERUI: "true"
    ports:
      - "127.0.0.1:80:80"
  
  db:
    image: postgres:14.3
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: password
    expose:
      - "5432"
    ports:
      - "5432:5432"